# -*- coding: utf-8 -*-
"""Taller11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gEn9znxsEFmgOWGWRqBTUspFfOSL-mkt
"""

class Nodo:
    def __init__(self, valor):
        self.valor = valor
        self.izquierda = None
        self.derecha = None

def preorden(nodo):
    if nodo is not None:
        print(nodo.valor)  # Visita el nodo actual
        preorden(nodo.izquierda)  # Recorre el subárbol izquierdo
        preorden(nodo.derecha)  # Recorre el subárbol derecho

def inorden(nodo):
    if nodo is not None:
        inorden(nodo.izquierda)  # Recorre el subárbol izquierdo
        print(nodo.valor)  # Visita el nodo actual
        inorden(nodo.derecha)  # Recorre el subárbol derecho

def postorden(nodo):
    if nodo is not None:
        postorden(nodo.izquierda)  # Recorre el subárbol izquierdo
        postorden(nodo.derecha)  # Recorre el subárbol derecho
        print(nodo.valor)  # Visita el nodo actual

# Llamamos a las funciones de recorrido desde la raíz del árbol
arbol = Nodo(1)
arbol.izquierda = Nodo(2)
arbol.derecha = Nodo(3)
arbol.izquierda.izquierda = Nodo(4)
arbol.izquierda.derecha = Nodo(5)

print("Recorrido en Preorden:")
preorden(arbol)

print("Recorrido en Inorden:")
inorden(arbol)

print("Recorrido en Postorden:")
postorden(arbol)